import { Fragment } from "react";
import axios from "axios";

// next
import { GetStaticProps } from "next";
import Head from "next/head";

// views
import { Home } from "views";

// types
import { Product } from "types/product";

interface Props {
  products: Product[];
}

function Main({ products }: Props) {
  return (
    <Fragment>
      <Head>
        <title>App - products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home products={products} />
    </Fragment>
  );
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  return axios
    .get<{ data: Product[]; status: number }>(
      "http://localhost:3000/api/products"
    )
    .then(({ data }) => {
      const { data: products } = data;
      return {
        props: {
          products,
        },
      };
    })
    .catch((error) => {
      console.error(error);
      return {
        props: {
          products: [],
        },
      };
    });
};

export default Main;
