import { GetStaticProps } from "next";
import Head from "next/head";
import axios from "axios";
import { Product } from "types/product";

interface Props {
  products: Product[];
}

function Home({ products }: Props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ul>
          {products.map((product) => (
            <li key={product.id}>{product.name}</li>
          ))}
        </ul>
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  return axios
    .get<{ data: Product[]; status: number }>(
      "http://localhost:3000/api/products"
    )
    .then(({ data }) => {
      const { data: products } = data;
      return {
        props: {
          products,
        },
      };
    })
    .catch((error) => {
      console.error(error);
      return {
        props: {
          products: [],
        },
      };
    });
};

export default Home;
